version: '3.7'

services:
    minio:
        image: minio/minio
        container_name: minio
        volumes:
            - ./data:/data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=minioadmin
            - MINIO_SECRET_KEY=minioadmin
        command: server /data
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:10000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3

